#!/usr/bin/env node
// ClaimTape CLI — optional tiny companion
// Usage:
//   echo "AI text" | node cli/claimtape.js
//   node cli/claimtape.js --answer answer.txt --evidence trace.jsonl
//   node cli/claimtape.js --answer answer.txt --evidence trace.jsonl --format json

import { readFileSync, existsSync } from 'fs';
import { createRequire } from 'module';

// Inline the analyzer (avoids transpile dependency for CLI usage)
// We import the source directly as ES module
import { analyze, generateMarkdownReport, generateJSONExport } from '../src/analyzer.js';

const args = process.argv.slice(2);

function getArg(flag) {
  const i = args.indexOf(flag);
  if (i !== -1 && args[i + 1]) return args[i + 1];
  return null;
}

const answerFile = getArg('--answer');
const evidenceFile = getArg('--evidence');
const format = getArg('--format') || 'text';
const help = args.includes('--help') || args.includes('-h');

if (help) {
  console.log(`
ClaimTape CLI v1.0.0
Did the AI actually prove that?

Usage:
  echo "AI text" | node cli/claimtape.js
  node cli/claimtape.js --answer answer.txt --evidence trace.jsonl
  node cli/claimtape.js --answer answer.txt --evidence trace.jsonl --format json
  node cli/claimtape.js --answer answer.txt --evidence trace.jsonl --format markdown

Options:
  --answer <file>    File containing AI answer text (or pipe via stdin)
  --evidence <file>  File containing evidence text (.jsonl/.md/.txt)
  --format <fmt>     Output format: text (default) | json | markdown
  -h, --help         Show this help

No API key required. All analysis runs locally.
`);
  process.exit(0);
}

async function main() {
  let answerText = '';
  let evidenceText = '';

  // Read answer
  if (answerFile) {
    if (!existsSync(answerFile)) {
      console.error(`Error: answer file not found: ${answerFile}`);
      process.exit(1);
    }
    answerText = readFileSync(answerFile, 'utf8');
  } else if (!process.stdin.isTTY) {
    // Read from stdin
    const chunks = [];
    for await (const chunk of process.stdin) chunks.push(chunk);
    answerText = Buffer.concat(chunks).toString('utf8');
  }

  if (!answerText.trim()) {
    console.error('Error: No answer text provided. Use --answer <file> or pipe text via stdin.');
    console.error('Use --help for usage.');
    process.exit(1);
  }

  // Read evidence
  if (evidenceFile) {
    if (!existsSync(evidenceFile)) {
      console.error(`Warning: evidence file not found: ${evidenceFile}`);
    } else {
      evidenceText = readFileSync(evidenceFile, 'utf8');
    }
  }

  const results = analyze(answerText, evidenceText);

  if (format === 'json') {
    console.log(generateJSONExport(results, answerText, evidenceText));
    return;
  }

  if (format === 'markdown') {
    console.log(generateMarkdownReport(results));
    return;
  }

  // Default: pretty text output
  const { claims, score, stats, riskFlags } = results;
  const scoreColor = score >= 70 ? '\x1b[32m' : score >= 45 ? '\x1b[33m' : '\x1b[31m';
  const reset = '\x1b[0m';
  const bold = '\x1b[1m';
  const dim = '\x1b[2m';

  console.log(`\n${bold}ClaimTape Report${reset}`);
  console.log('─'.repeat(50));
  console.log(`${bold}Trust Score:${reset} ${scoreColor}${score}/100${reset}`);
  console.log(`${dim}Evidence: ${results.hasEvidence ? 'Provided' : 'Not provided'}${reset}\n`);

  console.log(`Total claims: ${stats.total}`);
  console.log(`  ✅ Supported:    ${stats.supported}`);
  console.log(`  ⚠️  Unsupported:  ${stats.unsupported}`);
  console.log(`  ❌ Contradicted: ${stats.contradicted}`);
  console.log(`  🔍 Needs Human:  ${stats.needs_human}`);

  if (riskFlags.length > 0) {
    console.log(`\n⚠️  Risk Flags: ${riskFlags.join(', ')}`);
  }

  console.log('\n' + '─'.repeat(50));
  console.log(`${bold}Claims:${reset}\n`);

  const statusIcons = { supported: '✅', unsupported: '⚠️', contradicted: '❌', needs_human: '🔍' };

  claims.forEach(c => {
    const icon = statusIcons[c.status] || '?';
    const riskNote = c.isRisky ? ' 🚩' : '';
    console.log(`${icon}${riskNote} Claim ${c.id}: ${c.claim.substring(0, 80)}${c.claim.length > 80 ? '…' : ''}`);
    if (c.evidenceMatches.length > 0) {
      console.log(`   ${dim}Evidence: ${c.evidenceMatches.slice(0, 5).join(', ')}${reset}`);
    }
    if (c.conflictSignals.length > 0) {
      console.log(`   \x1b[31mConflicts: ${c.conflictSignals.join(', ')}${reset}`);
    }
    console.log();
  });

  console.log(`${dim}─ Generated by ClaimTape v1.0.0 — local, private, no API key ─${reset}\n`);
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
